In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("/content/ArtificialPatientTreatment.csv")

In [3]:
df.head(20)

      patient           action  org:resource              DateTime
0   patient 0    First consult      Dr. Anna   2017-01-02 11:40:11
1   patient 0       Blood test           Lab   2017-01-02 12:47:33
2   patient 0    Physical test   Nurse Jesse   2017-01-02 12:53:50
3   patient 0   Second consult      Dr. Anna   2017-01-02 16:21:06
4   patient 0          Surgery   Dr. Charlie   2017-01-05 13:23:09
5   patient 0    Final consult       Dr. Ben   2017-01-09 08:29:28
6   patient 1    First consult      Dr. Anna   2017-01-02 12:50:35
7   patient 1    Physical test   Nurse Jesse   2017-01-02 13:59:14
8   patient 1       Blood test           Lab   2017-01-02 14:20:19
9   patient 1       X-ray scan        Team 1   2017-01-06 09:13:40
10  patient 1   Second consult      Dr. Anna   2017-01-06 10:38:04
11  patient 1         Medicine      Pharmacy   2017-01-06 11:47:36
12  patient 1    Final consult      Dr. Anna   2017-01-06 16:49:21
13  patient 2    First consult      Dr. Anna   2017-01-04 10:02:49
14  patient 2    Physical test   Nurse Jesse   2017-01-06 09:05:01
15  patient 2       X-ray scan        Team 2   2017-01-10 08:05:47
16  patient 2       Blood test           Lab   2017-01-10 09:12:09
17  patient 2   Second consult      Dr. Anna   2017-01-12 16:32:00
18  patient 2         Medicine      Pharmacy   2017-01-13 10:32:51
19  patient 2    Final consult       Dr. Ben   2017-01-17 11:54:48

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patient        690 non-null    object
 1    action        690 non-null    object
 2    org:resource  690 non-null    object
 3    DateTime      690 non-null    object
dtypes: object(4)
memory usage: 21.7+ KB

In [5]:
df.describe()

          patient          action  org:resource              DateTime
count         690             690           690                   690
unique        100               8            13                   690
top     patient 1   First consult      Dr. Anna   2017-05-31 12:46:43
freq            7             100           158                     1

In [6]:
df.shape

(690, 4)

In [7]:
df.isnull().sum()

patient          0
 action          0
 org:resource    0
 DateTime        0
dtype: int64

In [16]:
df.columns = df.columns.str.strip()

In [17]:
df.head()

,patient,action,org:resource,DateTime,DateTime Change,NextActivity
0,patient 0,First consult,Dr. Anna,2017-01-02 11:40:11,2017-01-02 11:40:11,Blood test
1,patient 0,Blood test,Lab,2017-01-02 12:47:33,2017-01-02 12:47:33,Physical test
2,patient 0,Physical test,Nurse Jesse,2017-01-02 12:53:50,2017-01-02 12:53:50,Second consult
3,patient 0,Second consult,Dr. Anna,2017-01-02 16:21:06,2017-01-02 16:21:06,Surgery
4,patient 0,Surgery,Dr. Charlie,2017-01-05 13:23:09,2017-01-05 13:23:09,Final consult

In [18]:
df['DateTimeClean'] = pd.to_datetime(df['DateTime'])

In [21]:
df.head()

,patient,action,org:resource,DateTime,DateTime Change,NextActivity,DateTimeClean
0,patient 0,First consult,Dr. Anna,2017-01-02 11:40:11,2017-01-02 11:40:11,Blood test,2017-01-02 11:40:11
1,patient 0,Blood test,Lab,2017-01-02 12:47:33,2017-01-02 12:47:33,Physical test,2017-01-02 12:47:33
2,patient 0,Physical test,Nurse Jesse,2017-01-02 12:53:50,2017-01-02 12:53:50,Second consult,2017-01-02 12:53:50
3,patient 0,Second consult,Dr. Anna,2017-01-02 16:21:06,2017-01-02 16:21:06,Surgery,2017-01-02 16:21:06
4,patient 0,Surgery,Dr. Charlie,2017-01-05 13:23:09,2017-01-05 13:23:09,Final consult,2017-01-05 13:23:09

In [23]:
df = df.sort_values(by=['patient','DateTimeClean'])

In [24]:
df.head()

,patient,action,org:resource,DateTime,DateTime Change,NextActivity,DateTimeClean
0,patient 0,First consult,Dr. Anna,2017-01-02 11:40:11,2017-01-02 11:40:11,Blood test,2017-01-02 11:40:11
1,patient 0,Blood test,Lab,2017-01-02 12:47:33,2017-01-02 12:47:33,Physical test,2017-01-02 12:47:33
2,patient 0,Physical test,Nurse Jesse,2017-01-02 12:53:50,2017-01-02 12:53:50,Second consult,2017-01-02 12:53:50
3,patient 0,Second consult,Dr. Anna,2017-01-02 16:21:06,2017-01-02 16:21:06,Surgery,2017-01-02 16:21:06
4,patient 0,Surgery,Dr. Charlie,2017-01-05 13:23:09,2017-01-05 13:23:09,Final consult,2017-01-05 13:23:09

In [26]:
df = df.drop(['DateTime Change','NextActivity'],axis = 1)

In [27]:
df.head()

,patient,action,org:resource,DateTime,DateTimeClean
0,patient 0,First consult,Dr. Anna,2017-01-02 11:40:11,2017-01-02 11:40:11
1,patient 0,Blood test,Lab,2017-01-02 12:47:33,2017-01-02 12:47:33
2,patient 0,Physical test,Nurse Jesse,2017-01-02 12:53:50,2017-01-02 12:53:50
3,patient 0,Second consult,Dr. Anna,2017-01-02 16:21:06,2017-01-02 16:21:06
4,patient 0,Surgery,Dr. Charlie,2017-01-05 13:23:09,2017-01-05 13:23:09

In [29]:
df['NextActivity'] = df.groupby('patient')['action'].shift(-1)

In [32]:
df['NextActivity'] = df['NextActivity'].fillna('[END]')

In [34]:
df['NextActivity'].head(20)

0          Blood test
1       Physical test
2      Second consult
3             Surgery
4       Final consult
5               [END]
6       Physical test
7          Blood test
8          X-ray scan
9      Second consult
10           Medicine
11      Final consult
12              [END]
68      Physical test
69         Blood test
70         X-ray scan
71     Second consult
72           Medicine
73      Final consult
74              [END]
Name: NextActivity, dtype: object